name: Deploy to AWS Lambda

on:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    if: github.actor == ${{ vars.ALLOWED_USER }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2

      with:
        aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_SECRET }}
        aws-region: ap-northeast-2

    - name: Package Lambda function
      run: |
        zip -r lambda_function.zip src

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name kiteapp-image-transformation --zip-file fileb://lambda_function.zip
      env:
        AWS_DEFAULT_REGION: ap-northeast-2 
